language: node_js
node_js:
  - "8.11.1"
deploy:
  provider: firebase
  project: proto-notes
  skip_cleanup: true
  token:
    secure: "rm9EAIyVT7M+S9z7yay2ov0JToe1HZoSesnfx6Ta0Aac3JQr14/L2FevOJpQHKaNhvrP/C4RVKDWj42BF/iaO+oCnvXPdReJf8B9Un8ELZJJD8ZZOOr0HzUjAfw7KAu1qsSolUNBr+csEe9045jXF4n8dNxTf715xEQIIfQEzDHJMuq169wwf1KYFDc0OvxGldWn2mc54n1aY7OzcttbzkAnxGFYm9V2KQj3X8KZgIeSSZtXm7K8v47QcRp+ersgyKFW+J/g+nVnxGlUBZ3uKYTWIFIXzTldR3tgxAteKzlFKAaREUyR+FCmds9qsjZjOZQ8626scGUtFAcxmYXWkZefNwxdTOiQmUeFUKWPI+15zHJLPbLlL8wI78vwRqjdx732PNMNOlDrjCOCLksFhGLUYhBD4pj8ecQg72McnxdKjHomnLVgGuGItC1U+aQMTzxAVBzU5qQ2MdC+RL4O5QCZmhRaFceAwVaoUm1octZylO/FdtzPAm7wooouV1Xqxw8py2GN9lhFhZiLyBGPfSEwEB1lbrXR5tVBbDUeooz07uCpfVqoWWw4ntY1UmYGhDEfeniJ27x3QS2W0XjjLMiN9yqZtZEXPuS6C0BffhWFbjzU+b7BiN139nNUXm9pzrfNb0747yvME6etAY5qNDHf0B1A0QE7vgoLK9tSvn8="